openapi: 3.0.0
info:
  title: Babies And Mothers
  contact: {}
  version: '1.0'
servers:
- url: https://baby-and-mother-1812.onrender.com/api/v1
  variables: {}
- url: http://localhost:1812/api/v1
  variables: {}
paths:
  /auth/signup:
    post:
      tags:
      - Authentication
      summary: Signup With Reset code
      operationId: SignupWithResetcode
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SignupWithResetcodeRequest'
              - example:
                  email: mohamedasmr98@gmail.com
                  firstName: Amr
                  lastName: H
                  password: '123456'
                  confirmPassword: '123456'
            example:
              email: mohamedasmr98@gmail.com
              firstName: Amr
              lastName: H
              password: '123456'
              confirmPassword: '123456'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /auth/login:
    post:
      tags:
      - Authentication
      summary: Login
      operationId: Login
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/LoginRequest'
              - example:
                  email: amr.flutter.dev@gmail.com
                  password: '123456'
            example:
              email: amr.flutter.dev@gmail.com
              password: '123456'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /auth/varifyResetCode:
    post:
      tags:
      - Authentication
      summary: Varify Reset Code
      operationId: VarifyResetCode
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/VarifyResetCodeRequest'
              - example:
                  resetCode: '683614'
            example:
              resetCode: '683614'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /auth/google:
    get:
      tags:
      - Authentication
      summary: Login With Google
      operationId: LoginWithGoogle
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /posts:
    get:
      tags:
      - Community
      summary: Get All Posts
      operationId: GetAllPosts
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Community
      summary: Post
      operationId: Post
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            encoding: {}
            schema:
              required:
              - text
              - image
              type: object
              properties:
                text:
                  type: string
                  example: hasdsadasdjasdas55sad35as
                image:
                  type: string
                  format: binary
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /posts/{id}:
    patch:
      tags:
      - Community
      summary: Update My Posts
      operationId: UpdateMyPosts
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            encoding: {}
            schema:
              required:
              - text
              - image
              type: object
              properties:
                text:
                  type: string
                  example: Test Two
                image:
                  type: string
                  format: binary
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /posts/{id}/like:
    get:
      tags:
      - Community
      summary: Get All Likes for this post
      operationId: GetAllLikesforthispost
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    post:
      tags:
      - Community
      summary: Add Like Post
      operationId: AddLikePost
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
    delete:
      tags:
      - Community
      summary: Remove Like From Post
      operationId: RemoveLikeFromPost
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /posts/{id}/comment:
    get:
      tags:
      - Community
      summary: Get All Comment for this post
      operationId: GetAllCommentforthispost
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    post:
      tags:
      - Community
      summary: Add Comment To Post
      operationId: AddCommentToPost
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/AddCommentToPostRequest'
              - example:
                  text: Nice comment
            example:
              text: Nice comment
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
    patch:
      tags:
      - Community
      summary: Update Comment To Post
      operationId: UpdateCommentToPost
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateCommentToPostRequest'
              - example:
                  text: Nice comment Test
            example:
              text: Nice comment Test
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /posts/{idPost}/comment/{id]:
    delete:
      tags:
      - Community
      summary: Remove Comment From Post
      operationId: RemoveCommentFromPost
      parameters:
      - name: idPost
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /weeks/add:
    post:
      tags:
      - Weeks
      summary: Create Week
      operationId: CreateWeek
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateWeekRequest'
              - example:
                  title: l
                  week: frist week
                  headline: Advice
                  content: AAAA
            example:
              title: l
              week: frist week
              headline: Advice
              content: AAAA
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /weeks/search/{id}:
    get:
      tags:
      - Weeks
      summary: Read Week
      operationId: ReadWeek
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /weeks/update/{id}:
    patch:
      tags:
      - Weeks
      summary: Update Week
      operationId: UpdateWeek
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateWeekRequest'
              - example:
                  title: Mango
                  content: AAAA
            example:
              title: Mango
              content: AAAA
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /weeks/delete/{id}:
    delete:
      tags:
      - Weeks
      summary: Delete Week
      operationId: DeleteWeek
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
components:
  schemas:
    SignupWithResetcodeRequest:
      title: SignupWithResetcodeRequest
      required:
      - email
      - firstName
      - lastName
      - password
      - confirmPassword
      type: object
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string
        confirmPassword:
          type: string
      example:
        email: mohamedasmr98@gmail.com
        firstName: Amr
        lastName: H
        password: '123456'
        confirmPassword: '123456'
    LoginRequest:
      title: LoginRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: amr.flutter.dev@gmail.com
        password: '123456'
    VarifyResetCodeRequest:
      title: VarifyResetCodeRequest
      required:
      - resetCode
      type: object
      properties:
        resetCode:
          type: string
      example:
        resetCode: '683614'
    AddCommentToPostRequest:
      title: AddCommentToPostRequest
      required:
      - text
      type: object
      properties:
        text:
          type: string
      example:
        text: Nice comment
    UpdateCommentToPostRequest:
      title: UpdateCommentToPostRequest
      required:
      - text
      type: object
      properties:
        text:
          type: string
      example:
        text: Nice comment Test
    CreateWeekRequest:
      title: CreateWeekRequest
      required:
      - title
      - week
      - headline
      - content
      type: object
      properties:
        title:
          type: string
        week:
          type: string
        headline:
          type: string
        content:
          type: string
      example:
        title: l
        week: frist week
        headline: Advice
        content: AAAA
    UpdateWeekRequest:
      title: UpdateWeekRequest
      required:
      - title
      - content
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      example:
        title: Mango
        content: AAAA
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: Authentication
- name: Community
- name: Weeks